name: Hello World
on:
  push:
    branches:
      - main

jobs:
  hello:
    name: Hello Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bin/helloworld.sh ${{ github.ref_name }}
